apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: dell-r640-rack3-u14
  namespace: openshift-machine-api
  labels:
    hardware.lifecycle/stage: validating
    hardware.lifecycle/model: dell-r640
    hardware.lifecycle/rack: rack3
    hardware.lifecycle/unit: u14
  annotations:
    inspect.metal3.io: enabled
spec:
  online: true

  bootMACAddress: "4c:d9:8f:26:6e:3c"
  bootMode: UEFI

  bmc:
    address: "redfish-virtualmedia+https://192.168.31.11/redfish/v1/Systems/System.Embedded.1"
    credentialsName: dell-r640-rack3-u14-bmc-secret
    disableCertificateVerification: true

  rootDeviceHints:
    deviceName: /dev/sdb